# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e8d7d45b5610d4b7f7787130e91a795ef0a425925e4029b789a9d61b67a86299cf4b703961d4d6babba648175f17379447e7d1e4caae4e1d05b6cd4a461800b

test:
  secret_key_base: 2df41e509df1b03e53281753fb7c212cfe75208a59e1ce7a4a1214ff287bc75d4da8282732630f8980635041f6e891c384e251ac94667698ed65961dbd7bcece

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
